openapi: 3.0.0
info:
  title: Eva Journey API
  description: API para gerenciamento de jornadas de funcionários
  version: 1.0.0

servers:
  - url: http://localhost:3000
    description: Servidor de desenvolvimento

paths:
  /api/employee-journeys:
    post:
      summary: Associa uma jornada a um funcionário
      description: Cria uma nova associação entre um funcionário e uma jornada, agendando as ações da jornada
      tags:
        - Employee Journeys
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - employeeId
                - journeyId
                - startDate
              properties:
                employeeId:
                  type: string
                  description: ID do funcionário
                  example: "507f1f77bcf86cd799439011"
                journeyId:
                  type: string
                  description: ID da jornada
                  example: "507f1f77bcf86cd799439012"
                startDate:
                  type: string
                  format: date-time
                  description: Data de início da jornada
                  example: "2024-03-20T10:00:00Z"
      responses:
        '201':
          description: Jornada associada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "507f1f77bcf86cd799439013"
                      employeeId:
                        type: string
                        example: "507f1f77bcf86cd799439011"
                      journeyId:
                        type: string
                        example: "507f1f77bcf86cd799439012"
                      startDate:
                        type: string
                        format: date-time
                        example: "2024-03-20T10:00:00Z"
                      status:
                        type: string
                        enum: [pending, in_progress, completed]
                        example: "pending"
                      currentActionIndex:
                        type: integer
                        example: 0
                      completedActions:
                        type: array
                        items:
                          type: string
                        example: []
        '500':
          description: Erro ao associar jornada
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Employee not found"

  /api/employee-journeys/{employeeId}:
    get:
      summary: Lista as jornadas de um funcionário
      description: Retorna todas as jornadas associadas a um funcionário específico
      tags:
        - Employee Journeys
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: string
          description: ID do funcionário
          example: "507f1f77bcf86cd799439011"
      responses:
        '200':
          description: Lista de jornadas retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "507f1f77bcf86cd799439013"
                        employeeId:
                          type: string
                          example: "507f1f77bcf86cd799439011"
                        journeyId:
                          type: string
                          example: "507f1f77bcf86cd799439012"
                        startDate:
                          type: string
                          format: date-time
                          example: "2024-03-20T10:00:00Z"
                        status:
                          type: string
                          enum: [pending, in_progress, completed]
                          example: "pending"
                        currentActionIndex:
                          type: integer
                          example: 0
                        completedActions:
                          type: array
                          items:
                            type: string
                          example: []
        '500':
          description: Erro ao buscar jornadas
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  error:
                    type: string
                    example: "Error fetching employee journeys"

components:
  schemas:
    EmployeeJourney:
      type: object
      properties:
        id:
          type: string
          example: "507f1f77bcf86cd799439013"
        employeeId:
          type: string
          example: "507f1f77bcf86cd799439011"
        journeyId:
          type: string
          example: "507f1f77bcf86cd799439012"
        startDate:
          type: string
          format: date-time
          example: "2024-03-20T10:00:00Z"
        status:
          type: string
          enum: [pending, in_progress, completed]
          example: "pending"
        currentActionIndex:
          type: integer
          example: 0
        completedActions:
          type: array
          items:
            type: string
          example: []

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          example: "Error message" 